services:
  web:
    build: .
    command: sh -c "flask db upgrade && gunicorn -b 0.0.0.0:5000 'app:create_app()'"
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://uploader:securepassword@db:5432/file_upload_db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: file_upload_db
      POSTGRES_USER: uploader
      POSTGRES_PASSWORD: securepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
